### PR TITLE
DelayAfter attribute improvement

### PR DESCRIPTION
**Pull request by ihmpavel**
Hi, this PR includes

- Refactored code
- Updated dependencies
- Added function property to `delayAfter` option

The code is working - tested and linted

### CODE REVIEW

**Comment by nfriedly** [comment]
This looks great, thanks!

**Comment by nfriedly** [comment]
I'm on my phone right now but I'll get a release out to npm soon, probably later today

**Comment by nfriedly** [comment]
Op, one thing I forgot: can you add a new test with `delayAfter` as a function?

**Comment by ihmpavel** [comment]
Hi, I have added a new test and I refactored the code just a little bit.

**Comment by nfriedly** [comment]
Thanks! It should be published as v1.2.0 shortly.

**Pull request merged**
