### PR TITLE
Update express-slow-down.js

### PR DESCRIPTION
**Pull request by aannoune**
Adding optional headers (as express-limit-rate does ).
I just set default to false : @nfriedly , i let you chose if it should be true or not

### CODE REVIEW

**Comment by aannoune** [comment]
I can understand why did the CI failed :/

**Comment by nfriedly** [comment]
Oh, yea, good idea. I think defaulting to `false` is a good idea here.

I think I know why CI failed - I updated the dependencies the other day to resolve a vulnerability in one of the dev dependencies, but the newer version doesn't support Node.js < 10, so I need to bump the tests to target more recent versions of node.js

**Comment by nfriedly** [comment]
Should get published in v1.4.0 whenever Travis CI gets around to it (although it's been a little slow lately)...

**Comment by aannoune** [comment]
Cool 
I might add some contributions in the next weeks if you don't mind ;)

**Pull request merged**
